name: dsindy-env
channels:
  - conda-forge
  - MOSEK
dependencies:
  - python=3.7.12
  - pandas=1.3.5
  - scikit-learn=1.0.2
  - notebook=6.4.10
  - nbconvert=6.5.0 # Uncomment if you plan on exporting notebooks
  - plotly=5.7.0
  - python-kaleido=0.2.1  # Needed to export static images from plotly
  - seaborn=0.11.2
  - cvxopt=1.3.0
  - mosek=8.1.83 # Requires license
  - jupytext=1.13.8  # Uncomment if you plan on exporting notebooks
  - flake8=4.0.1
  - yapf=0.33.0
  - pip=22.0.4
  - pip:
    - sigfig==1.3.0
    - --editable /home/jacqui/projects/DSINDy/
